/* Dojo WebGL runtime — browser-native Project SEKAI-style practice engine. */
(()=>{"use strict";
let A=window.__PJSEKAI_APP__;if(!A){window.addEventListener("pjsekai-app-ready",()=>{A=window.__PJSEKAI_APP__;boot()},{once:true});return;}
const $=id=>document.getElementById(id),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),N=(v,d=0)=>Number.isFinite(+v)?+v:d;
const S={songs:null,diffs:null,vocals:null,selDiff:"expert",audio:new Audio(),notes:[],running:false,paused:false,starting:false,lead:2.5,seek:0,score:0,combo:0,best:0,life:1000,judged:0,total:0,counts:{PERFECT:0,GREAT:0,GOOD:0,BAD:0,MISS:0},timing:0,tn:0,held:new Map(),fx:[],pt:[],gl:null,buf:null,pr:null,geom:null,raf:0,last:0,keys:["D","F","J","K"],ro:null,clockStart:0};
S.audio.preload="auto";
const DIFF=["easy","normal","hard","expert","master","append"],LAB={easy:"Easy",normal:"Normal",hard:"Hard",expert:"Expert",master:"Master",append:"Append"};
const st=document.createElement("style");st.textContent="#dojoGameStageWrap{position:relative;overflow:hidden;aspect-ratio:16/9;min-height:320px;background:#050713;touch-action:none}#dojoGameCanvas{position:absolute;inset:0;width:100%;height:100%}.dojo-wgl-overlay{position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse at 50% 80%,transparent 30%,rgba(0,0,0,.45) 100%)}.dojo-wgl-pause{position:absolute;z-index:5;right:12px;top:12px;border:1px solid rgba(255,255,255,.2);background:rgba(5,8,20,.55);color:#fff;border-radius:999px;padding:8px 12px;font-weight:800}.dojo-wgl-status{position:absolute;z-index:4;left:12px;bottom:10px;padding:5px 9px;border-radius:999px;background:rgba(5,8,20,.5);color:rgba(255,255,255,.72);font:800 9px system-ui;letter-spacing:.08em;pointer-events:none}";document.head.appendChild(st);
function app(){const x=A.getState()||{};x.dojo=x.dojo||{};S.keys=(Array.isArray(x.dojo.keys)?x.dojo.keys:["D","F","J","K"]).slice(0,4);while(S.keys.length<4)S.keys.push(["D","F","J","K"][S.keys.length]);return x}
async function j(u){const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);return r.json()}
function beatSec(b,c){let x=c[0]||{beat:0,bpm:120,sec:0};for(let i=1;i<c.length;i++){if(c[i].beat>b)break;x=c[i]}return x.sec+(b-x.beat)*60/x.bpm}
function sus(text){
 const rows=String(text).split(/\r?\n/).map(x=>x.trim()).filter(x=>x[0]==="#"),meta=new Map(),data=[];
 for(const r of rows){const p=r.indexOf(":");if(p<0)continue;const h=r.slice(1,p),v=r.slice(p+1).trim();meta.set(h,v);data.push([h,v])}
 const tpb=+(String(meta.get("REQUEST")||"").match(/ticks_per_beat\s+(\d+)/)?.[1]||480),bars=[];
 for(const [h,v] of data)if(/^\d{3}02$/.test(h))bars.push({m:+h.slice(0,3),len:+v||4});
 bars.sort((a,b)=>a.m-b.m);if(!bars.length)bars.push({m:0,len:4});
 let tick=0,prev=bars[0],bm=[];for(const z of bars){if(z!==bars[0])tick+=(z.m-prev.m)*prev.len*tpb;bm.push({m:z.m,t:tick,len:z.len*tpb});prev=z}
 const off=m=>{let z=bm[0];for(const q of bm){if(q.m>m)break;z=q}return z.t+(m-z.m)*z.len/(bm.find(v=>v.m===z.m)?.len||4)};
 const beatAt=t=>t/tpb;
 const rowPoints=(h,v)=>{const m=+h.slice(0,3),c=h[3],lane=parseInt(h[4],36),channel=h[5]||"",len=bm.find(q=>q.m===m)?.len||4,a=String(v).match(/.{2}/g)||[],out=[];for(let i=0;i<a.length;i++){if(a[i]==="00")continue;out.push({tick:off(m)+i/a.length*len*tpb,lane,width:Math.max(1,parseInt(a[i][1],36)||1),type:parseInt(a[i][0],36),channel});}return out};
 const bpm=new Map(),changes=[],base=[],flicks=[],slides=new Map(),guides=new Map();
 for(const [h,v] of data){
  if(/^BPM[0-9A-Z]{2}$/.test(h)){bpm.set(h.slice(3),+v||120);continue}
  if(/^\d{3}08$/.test(h)){const key=String(v).trim().toUpperCase();changes.push({beat:0,bpm:bpm.get(key)||+v||120,rawTick:off(+h.slice(0,3))});continue}
  if(/^\d{3}1[0-9a-z]$/i.test(h))base.push(...rowPoints(h,v));
  else if(/^\d{3}5[0-9a-z]$/i.test(h))flicks.push(...rowPoints(h,v));
  else if(/^\d{3}3[0-9a-z][0-9a-z]$/i.test(h)){for(const q of rowPoints(h,v)){const k=q.channel||h.slice(5,6);if(!slides.has(k))slides.set(k,[]);slides.get(k).push(q)}}
  else if(/^\d{3}9[0-9a-z][0-9a-z]$/i.test(h)){for(const q of rowPoints(h,v)){const k=q.channel||h.slice(5,6);if(!guides.has(k))guides.set(k,[]);guides.get(k).push(q)}}
 }
 changes.sort((x,y)=>x.rawTick-y.rawTick);if(!changes.length)changes.push({beat:0,bpm:120,rawTick:0});if(changes[0].rawTick>0)changes.unshift({beat:0,bpm:changes[0].bpm,rawTick:0});
 let sec=0;for(let i=0;i<changes.length;i++){if(i)sec+=(changes[i].rawTick-changes[i-1].rawTick)/tpb*60/changes[i-1].bpm;changes[i].sec=sec}
 const beatSec2=b=>{let q=changes[0];for(const z of changes){if(z.rawTick> b*tpb)break;q=z}return q.sec+(b*tpb-q.rawTick)/tpb*60/q.bpm};
 const fm=new Map(flicks.map(q=>[(cl(q.lane-2,0,11))+"@"+q.tick,{dir:q.type===1?"up":q.type===3?"left":q.type===4?"right":"up"}]));
 const notes=[],criticalAt=new Set(base.filter(q=>q.type===2||q.type===6).map(q=>cl(q.lane-2,0,11)+"@"+q.tick));
 for(const q of base){
  const l=cl(q.lane-2,0,11),f=fm.get(l+"@"+q.tick),typ=q.type;
  if(typ===1||typ===2)notes.push({k:"tap",l,w:q.width,b:beatAt(q.tick),c:typ===2,f:f?.dir||null,t:!!f});
  else if(typ===5||typ===6)notes.push({k:"trace",l,w:q.width,b:beatAt(q.tick),c:typ===6,f:f?.dir||null,t:!!f});
 }
 const makeSlides=(map,guide)=>{for(const arr of map.values()){arr.sort((x,y)=>x.tick-y.tick);if(arr.length<2)continue;const points=arr.map(q=>({l:cl(q.lane-2,0,11),b:beatAt(q.tick),w:q.width,type:q.type}));const start=points.findIndex(q=>q.type===1);if(start<0)continue;const tail=points.slice(start);const end=tail.findIndex(q=>q.type===2);const pts=end>=0?tail.slice(0,end+1):tail;if(pts.length<2)continue;notes.push({k:guide?"traceHold":"hold",l:pts[0].l,w:pts[0].w,b:pts[0].b,e:pts[pts.length-1].b,c:criticalAt.has(pts[0].l+"@"+arr.find(q=>q.type===1)?.tick)||criticalAt.has(pts[pts.length-1].l+"@"+arr.find(q=>q.type===2)?.tick),path:pts,guide})}};
 makeSlides(slides,false);makeSlides(guides,true);
 notes.sort((x,y)=>x.b-y.b);
 const o=(+meta.get("WAVEOFFSET")||0)/1000;
 return{changes,notes:notes.map((n,i)=>({...n,id:i,hit:beatSec2(n.b)+o,end:n.e==null?0:beatSec2(n.e)+o})};
}
function setup(){
 const c=$("dojoGameCanvas"),w=$("dojoGameStageWrap");if(!c||!w)throw Error("Dojo 畫面不存在");
 S.gl=c.getContext("webgl",{antialias:true,alpha:false});if(!S.gl)throw Error("瀏覽器不支援 WebGL");
 const g=S.gl,v="attribute vec2 p;attribute vec4 c;varying vec4 v;void main(){gl_Position=vec4(p,0.,1.);v=c;}",f="precision mediump float;varying vec4 v;void main(){gl_FragColor=v;}";
 const sh=(t,s)=>{const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw Error("WebGL shader");return x};
 S.pr=g.createProgram();g.attachShader(S.pr,sh(g.VERTEX_SHADER,v));g.attachShader(S.pr,sh(g.FRAGMENT_SHADER,f));g.linkProgram(S.pr);S.buf=g.createBuffer();S.pp=g.getAttribLocation(S.pr,"p");S.cc=g.getAttribLocation(S.pr,"c");
 const rs=()=>{const r=w.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;g.viewport(0,0,c.width,c.height);S.geom={w:r.width,h:r.height,top:r.height*.11,hit:r.height*.88,tl:r.width*.30,tr:r.width*.70,bl:r.width*.045,br:r.width*.955}};rs();addEventListener("resize",rs,{passive:true});if(window.ResizeObserver){const ro=new ResizeObserver(rs);ro.observe(w);S.ro=ro}
 if(!w.querySelector(".dojo-wgl-overlay")){const o=document.createElement("div");o.className="dojo-wgl-overlay";w.appendChild(o);const q=document.createElement("div");q.className="dojo-wgl-status";q.textContent="WEBGL · DOJO";w.appendChild(q);S.status=q;const p=document.createElement("button");p.className="dojo-wgl-pause";p.type="button";p.textContent="Ⅱ";p.hidden=true;p.onclick=pause;w.appendChild(p);S.pause=p}
}
function V(x,y,c,a=1){return[x/S.geom.w*2-1,1-y/S.geom.h*2,...c,a]}
function poly(p,c,a=1){const g=S.gl,d=[];p.forEach(x=>d.push(...V(x[0],x[1],c,a)));g.bindBuffer(g.ARRAY_BUFFER,S.buf);g.bufferData(g.ARRAY_BUFFER,new Float32Array(d),g.STREAM_DRAW);g.useProgram(S.pr);g.enableVertexAttribArray(S.pp);g.enableVertexAttribArray(S.cc);g.vertexAttribPointer(S.pp,2,g.FLOAT,false,24,0);g.vertexAttribPointer(S.cc,4,g.FLOAT,false,24,8);g.drawArrays(g.TRIANGLE_FAN,0,p.length)}
function ln(p,c,a=1){if(p.length<2)return;const g=S.gl,d=[];p.forEach(x=>d.push(...V(x[0],x[1],c,a)));g.bindBuffer(g.ARRAY_BUFFER,S.buf);g.bufferData(g.ARRAY_BUFFER,new Float32Array(d),g.STREAM_DRAW);g.useProgram(S.pr);g.enableVertexAttribArray(S.pp);g.enableVertexAttribArray(S.cc);g.vertexAttribPointer(S.pp,2,g.FLOAT,false,24,0);g.vertexAttribPointer(S.cc,4,g.FLOAT,false,24,8);g.drawArrays(g.LINE_STRIP,0,p.length)}
function P(t){const g=S.geom,p=Math.pow(cl(t,0,1),.82);return{y:g.top+(g.hit-g.top)*p,l:g.tl+(g.bl-g.tl)*p,r:g.tr+(g.br-g.tr)*p}}
function X(l,t){const q=P(t),m=!!app().dojo?.mirror,l2=m?11-l:l;return q.l+(q.r-q.l)*(l2+.5)/12}
function W(t){const q=P(t);return(q.r-q.l)/12}
function drawScene(){
 const g=S.gl,h=S.geom;g.clearColor(.015,.02,.055,1);g.clear(g.COLOR_BUFFER_BIT);
 const pulse=S.running?(.5+.5*Math.sin((S.audio.currentTime||0)*Math.PI*2*2)):0;
 poly([[0,0],[h.w,0],[h.w,h.h],[0,h.h]],[.015,.02,.06]);
 poly([[h.tl,h.top],[h.tr,h.top],[h.br,h.h],[h.bl,h.h]],[.045,.075,.14]);
 for(let i=0;i<=12;i++){const a=i===0||i===12?.5:.12+.08*pulse;ln([[h.tl+(h.tr-h.tl)*i/12,h.top],[h.bl+(h.br-h.bl)*i/12,h.hit]],[.28,.72,1],a)}
 for(let i=1;i<9;i++){const p=i/9,y=h.top+(h.hit-h.top)*Math.pow(p,.82),l=h.tl+(h.bl-h.tl)*Math.pow(p,.82),r=h.tr+(h.br-h.tr)*Math.pow(p,.82);ln([[l,y],[r,y]],[.3,.55,.85],.08)}
 ln([[h.bl,h.hit],[h.br,h.hit]],[.55,.92,1],.9);
 ln([[h.tl,h.top],[h.tr,h.top]],[.25,.55,.9],.28);
}
function noteDraw(n,now){const p=cl(1-(n.hit-now)/S.lead,0,1),q=P(p),x=X(n.l,p),w=W(p)*n.w*.9,h=Math.max(7,w*.2),c=n.c?[1,.84,.16]:n.f?[1,.25,.38]:n.t?[.35,1,.72]:[.2,.9,1];poly([[x-w/2,q.y-h],[x+w/2,q.y-h],[x+w/2,q.y+h],[x-w/2,q.y+h]],c);poly([[x-w*.25,q.y-h*.4],[x+w*.25,q.y-h*.4],[x+w*.25,q.y+h*.4],[x-w*.25,q.y+h*.4]],[1,1,1],.18);if(n.f){const d=n.f==="left"?-1:n.f==="right"?1:0;ln([[x-d*w*.18,q.y-h*1.8+h],[x+d*w*.35,q.y-h*1.8],[x+d*w*.18,q.y-h*1.8+h]],[1,.55,.7],.95)}}
function holdDraw(n,now){if(n.end<=now)return;const path=n.path||[{l:n.l,b:n.b},{l:n.l,b:n.e}],pts=[];for(const z of path){const t=cl(1-((beatSec(z.b,S.prep.changes))-now)/S.lead,0,1),q=P(t);pts.push([X(z.l,t),q.y])}for(let i=0;i<pts.length-1;i++){const [x1,y1]=pts[i],[x2,y2]=pts[i+1],w1=W(cl(1-((beatSec(path[i].b,S.prep.changes))-now)/S.lead,0,1))*n.w*.42,w2=W(cl(1-((beatSec(path[i+1].b,S.prep.changes)+S.prep.filler)-now)/S.lead,0,1))*n.w*.42;poly([[x1-w1,y1],[x1+w1,y1],[x2+w2,y2],[x2-w2,y2]],n.c?[1,.82,.18]:[.12,.9,.68],.78)}}
function fx(l){const x=X(l,1),y=S.geom.hit;S.fx.push({x,y,t:0});for(let i=0;i<14;i++){const a=Math.random()*6.28,v=60+Math.random()*130;S.pt.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:0})}}
function effects(dt){for(const e of S.fx){e.t+=dt;const k=e.t/.45,r=12+65*k;ln([[e.x-r,e.y],[e.x+r,e.y]],[.55,.9,1],1-k);ln([[e.x,e.y-r],[e.x,e.y+r]],[1,.8,.3],1-k)}S.fx=S.fx.filter(e=>e.t<.45);for(const p of S.pt){p.t+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=170*dt;const a=1-p.t/.42;if(a>0)poly([[p.x-2,p.y-2],[p.x+2,p.y-2],[p.x+2,p.y+2],[p.x-2,p.y+2]],[.65,.95,1],a)}S.pt=S.pt.filter(p=>p.t<.42)}
function hud(j){const put=(id,v)=>{const e=$(id);if(e)e.textContent=v};put("dojoGameScore",String(Math.floor(S.score)).padStart(7,"0"));put("dojoGameCombo",S.combo);put("dojoGameAccuracy",(S.tn?Math.max(0,100-S.timing/S.tn*420):100).toFixed(2)+"%");const l=$("dojoGameLifeBar");if(l)l.style.width=cl(S.life/10,0,100)+"%";const x=$("dojoJudgeText");if(x)x.textContent=j||""}
function judge(n,d,allowFinish=true){const a=Math.abs(d),j=a<=.045?"PERFECT":a<=.085?"GREAT":a<=.11?"GOOD":a<=.14?"BAD":"MISS";S.counts[j]++;S.timing+=Math.min(a,.2);S.tn++;S.combo=j==="MISS"||j==="BAD"?0:S.combo+1;S.best=Math.max(S.best,S.combo);S.score+=j==="PERFECT"?1000:j==="GREAT"?700:j==="GOOD"?400:j==="BAD"?150:0;S.life=cl(S.life+(j==="MISS"?-65:j==="BAD"?-30:1),0,1000);n.done=true;S.judged++;hud(j);fx(n.l);if(allowFinish&&S.judged>=S.total)finish()}
function hit(l,type="tap"){if(!S.running||S.paused)return;const now=S.audio.currentTime-S.seek;let best=null,bd=.17;for(const n of S.notes)if(!n.done&&Math.floor(n.l/3)===l&&!(n.k==="hold"&&n.started)){const d=Math.abs(n.hit-now);if(d<bd){bd=d;best=n}}if(!best)return;if(type==="flick"&&!best.f)return;if(type==="tap"&&best.f)return;if(best.k==="hold"||best.k==="traceHold"){best.started=true;S.held.set(l,best);judge({...best,k:"tap"},now-best.hit,false);return}judge(best,now-best.hit)}
function release(l){const n=S.held.get(l);if(!n)return;S.held.delete(l);const now=S.audio.currentTime-S.seek;if(now<n.end-.08){n.done=true;S.judged++;S.combo=0;S.life=Math.max(0,S.life-45);hud("MISS");return}n.done=true;judge({...n,k:"tap",hit:n.end},now-n.end)}
function sweep(now){for(const n of S.notes)if(!n.done&&!n.started&&now-n.hit>.16)judge(n,.2);for(const [l,n] of S.held)if(now>n.end+.16)release(l);if(S.life<=0)finish()}
function loop(t){S.raf=requestAnimationFrame(loop);const dt=Math.min(.05,(t-(S.last||t))/1000);S.last=t;drawScene();if(!S.running)return;const now=S.audio.currentTime-S.seek;for(const n of S.notes){if(n.k==="hold"||n.k==="traceHold")holdDraw(n,now);else if(now>n.hit-S.lead&&now<n.hit+.17)noteDraw(n,now)}sweep(now);effects(dt);const p=S.notes.length?cl(now/(S.notes[S.notes.length-1].end||S.notes[S.notes.length-1].hit),0,1):0;if($("dojoGameProgressBar"))$("dojoGameProgressBar").style.width=p*100+"%";if(now>S.endAt+.5)finish()}
function finish(){if(!S.running)return;S.running=false;S.audio.pause();if(S.pause)S.pause.hidden=true;const rank=S.counts.MISS===0&&S.counts.BAD===0?"ALL PERFECT":S.counts.MISS<5?"CLEAR":"FAILED",r=$("dojoGameResult");if(r){r.hidden=false;r.innerHTML="<strong>"+rank+"</strong><span>"+S.best+" COMBO · "+String(Math.floor(S.score)).padStart(7,"0")+"</span><small>PERFECT "+S.counts.PERFECT+"　GREAT "+S.counts.GREAT+"　GOOD "+S.counts.GOOD+"　BAD "+S.counts.BAD+"　MISS "+S.counts.MISS+"</small>"}if($("dojoOpenPracticeBtn"))$("dojoOpenPracticeBtn").textContent="↻ 再玩一次";if($("dojoGameMessage"))$("dojoGameMessage").textContent=rank+" · "+S.best+" COMBO"}
function pause(){if(!S.running)return;if(S.paused){S.audio.play();S.paused=false;S.pause.textContent="Ⅱ"}else{S.audio.pause();S.paused=true;S.pause.textContent="▶"}}
async function data(){if(!S.songs){const [a,b,c]=await Promise.all([j("dojo-musics.json"),j("dojo-difficulties.json"),j("dojo-vocals.json").catch(()=>[])]);S.songs=a;S.diffs=b;S.vocals=c;const m=new Map();for(const d of b){const id=+d.musicId;if(!m.has(id))m.set(id,{});m.get(id)[String(d.musicDifficulty).toLowerCase()]=d}S.songs=S.songs.map(x=>({...x,difficulties:m.get(+x.id)||{}}))}}
function selection(){
 const title=$("dojoSelectedTitle")?.textContent?.trim()||"",id=+(localStorage.getItem("pjsekai-chart-last-song")||1);
 const m=S.songs.find(x=>x.title===title)||S.songs.find(x=>+x.id===id)||S.songs[0];
 if(!m)return null;
 let d=S.selDiff;
 const box=$("dojoDifficultyButtons");
 if(box){const a=box.querySelector(".active,[aria-pressed='true'],button.selected");if(a){const raw=(a.dataset.dojoDiff||a.dataset.difficulty||a.textContent||"").toLowerCase();const k=DIFF.find(x=>raw.includes(x));if(k)d=k}}
 if(!m.difficulties[d])d=DIFF.find(x=>m.difficulties[x])||"expert";
 return{m,d};
}

function expose(){window.__PJSEKAI_DOJO__={state:{get prepared(){if(!S.prep)return null;return{music:S.prep.music,difficulty:S.prep.difficulty,audioUrl:S.prep.audioUrl||"",vocal:S.prep.vocal||null,notes:S.prep.notes||[]}},get notes(){return S.notes.map(n=>({lane:n.l,kind:n.k,hit:n.hit,judged:!!n.done}))},get audio(){return S.audio},get running(){return S.running},get starting(){return S.starting},get score(){return S.score},get combo(){return S.combo},get judged(){return S.judged}}}}
async function prepareDefault(){try{await data();const q=selection();if(!q?.m)throw Error("歌曲資料尚未就緒");const url="https://assets.unipjsk.com/startapp/music/music_score/"+String(q.m.id).padStart(4,"0")+"_01/"+q.d,r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error("官方譜面載入失敗 HTTP "+r.status);const score=sus(await r.text()),filler=N(q.m.fillerSec,0);score.filler=filler;score.notes.forEach(n=>{n.hit+=filler;if(n.end)n.end+=filler});const v=S.vocals.find(x=>+x.musicId===+q.m.id&&x.musicVocalType==="original_song")||S.vocals.find(x=>+x.musicId===+q.m.id);const vn=v?.assetbundleName||String(q.m.id).padStart(4,"0")+"_01";S.prep={...score,music:q.m,difficulty:q.d,vocal:v||null,audioUrl:"https://storage.sekai.best/sekai-jp-assets/music/long/"+vn+"/"+vn+".wav",notes:score.notes.map(n=>({lane:n.l,kind:n.k,hit:n.hit,judged:false}))};return S.prep}catch(e){console.warn("[Dojo default prepare]",e);throw e}}
async function start(){if(S.running){pause();if($("dojoOpenPracticeBtn"))$("dojoOpenPracticeBtn").textContent=S.paused?"繼續打歌":"⏸ 暫停";return}if(S.starting)return;S.starting=true;try{const b=$("dojoOpenPracticeBtn");if(b){b.disabled=true;b.textContent="載入中…"}await data();const q=selection();if(!q?.m)throw Error("歌曲資料尚未就緒");const url="https://assets.unipjsk.com/startapp/music/music_score/"+String(q.m.id).padStart(4,"0")+"_01/"+q.d,r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error("官方譜面載入失敗 HTTP "+r.status);const score=sus(await r.text()),filler=N(q.m.fillerSec,0);score.filler=filler;score.notes.forEach(n=>{n.hit+=filler;if(n.end)n.end+=filler});const v=S.vocals.find(x=>+x.musicId===+q.m.id&&x.musicVocalType==="original_song")||S.vocals.find(x=>+x.musicId===+q.m.id),vn=v?.assetbundleName||String(q.m.id).padStart(4,"0")+"_01";S.prep={...score,music:q.m,difficulty:q.d,vocal:v||null,audioUrl:"https://storage.sekai.best/sekai-jp-assets/music/long/"+vn+"/"+vn+".wav"};S.notes=score.notes.map(x=>({...x}));S.total=S.notes.reduce((n,x)=>n+(x.k==="hold"||x.k==="traceHold"?2:1),0);S.score=0;S.combo=0;S.best=0;S.life=1000;S.judged=0;S.counts={PERFECT:0,GREAT:0,GOOD:0,BAD:0,MISS:0};S.timing=0;S.tn=0;S.held.clear();S.fx=[];S.pt=[];S.audio.pause();S.audio.src="https://storage.sekai.best/sekai-jp-assets/music/long/"+vn+"/"+vn+".wav";S.audio.load();const speed=N(app().dojo?.speed,10);S.lead=cl(3.1-(speed-1)*.14,1.5,3.1);S.seek=0;await new Promise((resolve,reject)=>{if(S.audio.readyState>=2){resolve();return}const ok=()=>{cleanup();resolve()};const bad=()=>{cleanup();reject(Error("官方音源載入失敗"))};const cleanup=()=>{S.audio.removeEventListener("canplay",ok);S.audio.removeEventListener("error",bad)};S.audio.addEventListener("canplay",ok,{once:true});S.audio.addEventListener("error",bad,{once:true});S.audio.load()});await S.audio.play();S.running=true;S.paused=false;S.endAt=Math.max(...S.notes.map(x=>x.end||x.hit),0)+.6;S.pause.hidden=false;S.status.textContent="PLAY · "+LAB[q.d];if($("dojoOpenPracticeBtn"))$("dojoOpenPracticeBtn").textContent="⏸ 暫停";if($("dojoGameResult"))$("dojoGameResult").hidden=true;if($("dojoGameSongTitle"))$("dojoGameSongTitle").textContent=q.m.title;if($("dojoGameSongMeta"))$("dojoGameSongMeta").textContent="官方音源 · "+LAB[q.d];hud("");}catch(e){if($("dojoGameMessage"))$("dojoGameMessage").textContent="⚠ "+(e.message||"開始失敗");A.toast?.(e.message||"Dojo 啟動失敗")}finally{S.starting=false;const b=$("dojoOpenPracticeBtn");if(b){b.disabled=false;if(!S.running)b.textContent="▶ 開始打歌"}}}
function bind(){const touch=new Map();const b=$("dojoOpenPracticeBtn");if(b){const n=b.cloneNode(true);b.replaceWith(n);n.addEventListener("click",start)}document.addEventListener("keydown",e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||""))return;const i=S.keys.findIndex(k=>String(k).toUpperCase()===e.key.toUpperCase());if(i<0||e.repeat)return;e.preventDefault();hit(i)});document.addEventListener("keyup",e=>{const i=S.keys.findIndex(k=>String(k).toUpperCase()===e.key.toUpperCase());if(i>=0)release(i)});document.addEventListener("pointerdown",e=>{
 const z=e.target.closest("[data-dojo-lane-zone]");
 if(z){e.preventDefault();const l=+z.dataset.dojoLaneZone;touch.set(e.pointerId,{l,x:e.clientX,y:e.clientY,t:performance.now()});hit(l);return}
 const w=$("dojoGameStageWrap");if(!w||!S.running)return;
 const r=w.getBoundingClientRect(),x=cl((e.clientX-r.left)/r.width,0,0.999),l=Math.floor(x*12)/3|0;
 touch.set(e.pointerId,{l,x:e.clientX,y:e.clientY,t:performance.now()});hit(l);
},{passive:false});document.addEventListener("pointermove",e=>{const q=touch.get(e.pointerId);if(!q||!S.running)return;const dx=e.clientX-q.x,dy=e.clientY-q.y;if(Math.hypot(dx,dy)>24){hit(q.l,"flick");touch.delete(e.pointerId)}},{passive:false});document.addEventListener("pointerup",e=>{const q=touch.get(e.pointerId);touch.delete(e.pointerId);if(q)release(q.l)});document.addEventListener("pointercancel",e=>{const q=touch.get(e.pointerId);touch.delete(e.pointerId);if(q)release(q.l)});document.addEventListener("click",e=>{const d=e.target.closest("[data-dojo-diff]");if(d)S.selDiff=d.dataset.dojoDiff||"expert"});$("dojoGameFullscreenBtn")?.addEventListener("click",async()=>{try{await $("dojoGameStageWrap")?.requestFullscreen?.()}catch(_){}});$("dojoGameResetBtn")?.addEventListener("click",()=>{S.running=false;S.audio.pause();if($("dojoGameResult"))$("dojoGameResult").hidden=true});}
async function boot(){try{expose();setup();bind();if(!S.raf)S.raf=requestAnimationFrame(loop);await data();await prepareDefault()}catch(e){console.warn("[Dojo WebGL]",e);const m=$("dojoGameMessage");if(m)m.textContent="⚠ Dojo 初始化失敗："+(e?.message||"未知錯誤")}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();