/* COMPLETE WEB DOJO ENGINE V2 */
(()=>{"use strict";
const q=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const E={canvas:null,ctx:null,audio:null,raf:0,running:false,notes:[],pointers:new Map(),effects:[],speed:1,offset:0,mirror:false,reverse:false,sudden:false,combo:0,maxCombo:0,score:0,counts:{perfect:0,great:0,good:0,bad:0,miss:0},bpm:120,duration:90,judgment:{perfect:45,great:90,good:140,bad:200},holdGrace:90,chartName:"Web Dojo",lastJudge:"—",audioCtx:null,
init(){const s=q("#dojoStage");if(!s)return;this.canvas=s.querySelector("canvas")||document.createElement("canvas");this.ctx=this.canvas.getContext("2d");s.innerHTML="";s.classList.add("pjsk-engine-stage");s.appendChild(this.canvas);this.audio=q("#dojoAudio");this.makeChart();this.bind(s);this.resize();addEventListener("resize",()=>this.resize());this.render()},
resize(){const r=this.canvas.getBoundingClientRect(),d=devicePixelRatio||1;this.canvas.width=r.width*d;this.canvas.height=r.height*d;this.ctx.setTransform(d,0,0,d,0,0)},
bind(s){this.audio?.addEventListener("play",()=>{this.running=true;cancelAnimationFrame(this.raf);this.loop()});this.audio?.addEventListener("pause",()=>{this.running=false;cancelAnimationFrame(this.raf);this.render()});this.audio?.addEventListener("seeked",()=>this.resetJudgments());this.audio?.addEventListener("loadedmetadata",()=>this.duration=this.audio.duration||this.duration);
q("#dojoPracticePlay")?.addEventListener("click",()=>this.toggle());q("#dojoPracticeStop")?.addEventListener("click",()=>this.stop());q("#dojoSpeed")?.addEventListener("input",e=>{this.speed=+e.target.value||1;if(this.audio)this.audio.playbackRate=this.speed});q("#dojoMirror")?.addEventListener("change",e=>this.mirror=e.target.checked);q("#dojoReverse")?.addEventListener("change",e=>this.reverse=e.target.checked);q("#dojoSudden")?.addEventListener("change",e=>this.sudden=e.target.checked);
q("#dojoAudioFile")?.addEventListener("change",e=>{const f=e.target.files?.[0];if(f){this.audio.src=URL.createObjectURL(f);this.audio.load();const n=q("#dojoAudioName");if(n)n.textContent=f.name}});
s.addEventListener("pointerdown",e=>{s.setPointerCapture?.(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,note:null,down:performance.now()});this.input(e,true,0,0)}, {passive:true});
s.addEventListener("pointermove",e=>{const p=this.pointers.get(e.pointerId);if(!p)return;p.x=e.clientX;p.y=e.clientY;if(p.note?.type==="trace"||p.note?.type==="slide")this.follow(p.note,e)}, {passive:true});
s.addEventListener("pointerup",e=>{const p=this.pointers.get(e.pointerId);if(p?.note?.type==="hold"||p?.note?.type==="slide")this.release(p.note);this.input(e,false,p?e.clientX-p.x:0,p?e.clientY-p.y:0);this.pointers.delete(e.pointerId)}, {passive:true});
s.addEventListener("pointercancel",e=>{const p=this.pointers.get(e.pointerId);if(p?.note)this.release(p.note);this.pointers.delete(e.pointerId)},{passive:true});
addEventListener("keydown",e=>{if(e.repeat)return;const m={a:0,s:1,d:2,f:3,j:8,k:9,l:10,";":11};if(m[e.key.toLowerCase()]!==undefined)this.hit(m[e.key.toLowerCase()],"tap",0,0,null);if(e.key===" ")this.toggle()})},
makeChart(){this.notes=[];let t=1.2,id=0;for(let i=0;i<240;i++){const lane=(i*7+i%4)%12;let type=i%23===0?"slide":i%17===0?"hold":i%11===0?"flick":i%13===0?"trace":"tap";const dur=type==="hold"?0.65:type==="slide"?0.9:0;this.notes.push({id:id++,time:t,lane,type,duration:dur,endLane:(lane+(i%2?3:-3)+12)%12,dir:i%4,hit:false,holdUntil:0,tickCount:0});t+=i%9===0?.24:i%5===0?.36:.46}this.duration=t+2},
resetJudgments(){for(const n of this.notes)n.hit=false,n.holdUntil=0,n.tickCount=0;n=>0;this.combo=0;this.score=0;this.counts={perfect:0,great:0,good:0,bad:0,miss:0};this.effects=[];this.render()},
time(){return this.audio?.currentTime||0},
toggle(){if(!this.audio)return;if(this.audio.paused)this.audio.play().catch(()=>{});else this.audio.pause()},
stop(){if(!this.audio)return;this.audio.pause();this.audio.currentTime=0;this.resetJudgments()},
window(ms){const a=Math.abs(ms);return a<=this.judgment.perfect?"perfect":a<=this.judgment.great?"great":a<=this.judgment.good?"good":a<=this.judgment.bad?"bad":null},
input(e,down,dx,dy){const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left;if(e.clientY-r.top<r.height*.65)return;let lane=clamp(Math.floor(x/r.width*12),0,11);if(this.mirror)lane=11-lane;const p=this.pointers.get(e.pointerId);if(down){const n=this.find(lane);if(n){this.hit(lane,"tap",dx,dy,e);if(p)p.note=n}}else if(p?.note?.type==="flick"){}},
find(lane){const now=this.time()*1000;let b=null,bd=Infinity;for(const n of this.notes){if(n.hit||n.lane!==lane)continue;const d=Math.abs(n.time*1000-now-this.offset);if(d<bd&&d<=this.judgment.bad+60)b=n,bd=d}return b},
hit(lane,type,dx,dy,event){const n=this.find(lane);if(!n)return;const delta=n.time*1000-this.time()*1000-this.offset;const j=this.window(delta);if(!j)return;if((n.type==="flick"||n.type==="slide")&&(Math.abs(dx)+Math.abs(dy)<12))return;n.hit=true;n.judgment=j;n.holdUntil=n.time+n.duration;this.counts[j]++;this.combo++;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=j==="perfect"?1000:j==="great"?800:j==="good"?500:100;this.lastJudge=j.toUpperCase();this.effects.push({lane,kind:j,life:.42,max:.42});this.sfx(n.type==="flick"?"flick":"tap");return n},
follow(n,e){if(!n.hit)return;const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left,lane=clamp(Math.floor(x/r.width*12),0,11);if(n.type==="slide"&&Math.abs(lane-n.endLane)<=1)this.effects.push({lane,kind:"trace",life:.15,max:.15})},
release(n){if(!n||!n.hit)return;if(n.type==="hold"||n.type==="slide"){const remain=Math.max(0,(n.holdUntil-this.time())*1000);if(remain<=this.holdGrace){this.combo++;this.score+=300;this.sfx("tap")}else{this.combo=0;this.counts.bad++;this.lastJudge="BAD";this.sfx("miss")}}},
sfx(k){try{this.audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=this.audioCtx.createOscillator(),g=this.audioCtx.createGain();o.type="triangle";o.frequency.value=k==="flick"?980:k==="miss"?160:720;g.gain.value=.035;g.gain.exponentialRampToValueAtTime(.0001,this.audioCtx.currentTime+.07);o.connect(g).connect(this.audioCtx.destination);o.start();o.stop(this.audioCtx.currentTime+.08)}catch{}},
loop(){if(!this.running)return;const t=this.time();for(const n of this.notes){if(!n.hit&&(t-n.time)*1000-this.offset>this.judgment.bad){n.hit=true;n.judgment="miss";this.counts.miss++;this.combo=0;this.lastJudge="MISS";this.effects.push({lane:n.lane,kind:"miss",life:.4,max:.4})}}this.render();this.raf=requestAnimationFrame(()=>this.loop())},
project(l,p,w,h){const z=Math.pow(clamp(p,0,1),1.6),spread=w*.76*(.06+.94*z),x=w/2+((l+.5)/12-.5)*spread,y=h*.08+(1-z)*h*.76;return{x,y,size:Math.max(9,spread/12)}},
render(){const ctx=this.ctx,r=this.canvas.getBoundingClientRect(),w=r.width,h=r.height;if(!w)return;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#070914");g.addColorStop(1,"#111a32");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
ctx.strokeStyle="rgba(255,255,255,.1)";ctx.lineWidth=1;for(let i=0;i<=12;i++){ctx.beginPath();ctx.moveTo(w/2+(i/12-.5)*w*.06,h*.05);ctx.lineTo(w*.12+i*w*.76/12,h*.93);ctx.stroke()}ctx.strokeStyle="rgba(255,255,255,.4)";ctx.beginPath();ctx.moveTo(w*.1,h*.84);ctx.lineTo(w*.9,h*.84);ctx.stroke();
const now=this.time(),travel=.95/(this.speed||1);for(const n of this.notes){if(n.hit&&n.type!=="hold"&&n.type!=="slide")continue;const p=1-(n.time-now)/travel;if(p<0||p>1.08)continue;if(this.sudden&&p<.45)continue;const l=this.mirror?11-n.lane:n.lane, a=this.project(l,p,w,h), tail=this.project(this.mirror?11-(n.endLane??n.lane):n.endLane??n.lane,1-(n.time+n.duration-now)/travel,w,h);
if(n.type==="hold"||n.type==="slide"){ctx.strokeStyle=n.type==="slide"?"#ffcf63":"#56dcef";ctx.lineWidth=Math.max(5,a.size*.55);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(tail.x,tail.y);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(tail.x,tail.y,Math.max(4,a.size*.35),0,Math.PI*2);ctx.fill()}
ctx.save();ctx.translate(a.x,a.y);ctx.shadowBlur=14;ctx.shadowColor=n.type==="flick"?"#ffd24d":"#63e9ff";ctx.fillStyle=n.type==="flick"?"#ffd24d":n.type==="trace"?"#75e7c0":"#f4fbff";ctx.beginPath();ctx.roundRect(-a.size*.7,-a.size*.7,a.size*1.4,a.size*1.4,5);ctx.fill();if(n.type==="flick"){ctx.fillStyle="#fff";ctx.beginPath();const d=n.dir%4;const pts=[[0,-a.size*1.2],[a.size*1.2,0],[0,a.size*1.2],[-a.size*1.2,0]][d];ctx.moveTo(pts[0],pts[1]);ctx.lineTo(-a.size*.45,-a.size*.35);ctx.lineTo(a.size*.45,-a.size*.35);ctx.closePath();ctx.fill()}ctx.restore()}
for(const e of this.effects){e.life-=1/60;if(e.life<=0)continue;ctx.save();ctx.globalAlpha=e.life/e.max;ctx.fillStyle=e.kind==="perfect"?"#fff":e.kind==="great"?"#ffe36b":e.kind==="good"?"#69dcff":e.kind==="miss"?"#ff6b86":"#75e7c0";ctx.font="900 14px sans-serif";ctx.textAlign="center";ctx.fillText(String(e.kind).toUpperCase(),w*(.12+(e.lane+.5)/12*.76),h*.79-(1-e.life/e.max)*35);ctx.restore()}
const C=q("#pjskCombo"),S=q("#pjskScore"),J=q("#pjskJudge");if(C)C.textContent=this.combo;if(S)S.textContent=String(Math.round(this.score)).padStart(7,"0");if(J)J.textContent=this.lastJudge}}
window.PJSekaiWebDojo=E;if(document.readyState==="loading")addEventListener("DOMContentLoaded",()=>E.init());else E.init();
})();